---
  name: Build and test
  
  on:
    push:
      branches:
        - master
  
  jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - name: Check out repository code
          uses: actions/checkout@v3
  
        - name: Install NodeJS
          uses: actions/setup-node@v3
          with:
            node-version: '18'
  
        - name: Install dependencies
          run: yarn install
  
        - name: Lint
          run: yarn lint
  
        - name: Build Docker Image
          uses: docker/build-push-action@v3
          with:
            context: .
            file: ./Dockerfile
            tags: tommavl/webapp:latest
            push: false
  